-- Push sync state for Gmail + Calendar webhooks (Milestones 1.2 / 1.3).
--
-- Gmail watches are per-user (one watch covers the whole mailbox); we
-- piggyback on the existing GmailSyncState row with a new expiration
-- column to track when the watch needs renewal.
ALTER TABLE "GmailSyncState"
  ADD COLUMN IF NOT EXISTS "watchExpiration" TIMESTAMP(3);

-- Calendar watches are per-calendar (we may eventually watch primary +
-- secondary calendars), so each needs its own channel state. The
-- channel id + resource id are generated by us and returned by Google;
-- both are required to stop a channel cleanly.
CREATE TABLE IF NOT EXISTS "CalendarWatchChannel" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "accountId" TEXT NOT NULL,
  "calendarId" TEXT NOT NULL,
  "channelId" TEXT NOT NULL,
  "resourceId" TEXT NOT NULL,
  "expiration" TIMESTAMP(3) NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "CalendarWatchChannel_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS
  "CalendarWatchChannel_accountId_calendarId_key"
  ON "CalendarWatchChannel"("accountId", "calendarId");
CREATE INDEX IF NOT EXISTS
  "CalendarWatchChannel_expiration_idx"
  ON "CalendarWatchChannel"("expiration");
