-- Phase 6.1 — Voice corpus indexing.
-- Three additions:
--   1. EmailMessage.fullBody — store the full RFC 822 body of outbound
--      mail so we can do real feature extraction (the 500-char snippet
--      isn't enough for signature / sentence-rhythm work).
--   2. VoiceProfile — one row per user, a snapshot of the learned voice
--      plus Jennifer's manual overrides. Regenerated by the worker on
--      each re-index; overrides persist across recomputation.
--   3. VoiceExample — one row per indexed outbound email, with the
--      deterministically-extracted features and a Voyage embedding for
--      few-shot retrieval (M6.3).

ALTER TABLE "EmailMessage" ADD COLUMN "fullBody" TEXT;

CREATE TABLE "VoiceProfile" (
    "id"                  TEXT NOT NULL,
    "userId"              TEXT NOT NULL,
    -- Aggregated by the worker from VoiceExample rows. Shape documented
    -- in src/lib/voice/profile.ts (greetingsByType, closingsByType,
    -- avgSentenceLenByType, signaturePhrases, neverSays).
    "learned"             JSONB NOT NULL DEFAULT '{}',
    -- Manual overrides from /settings/voice. Sticky across re-indexing.
    -- Shape: { removedPhrases: string[], assertedPatterns: {...} }.
    "overrides"           JSONB NOT NULL DEFAULT '{}',
    "indexedEmailCount"   INTEGER NOT NULL DEFAULT 0,
    "oldestIndexedAt"     TIMESTAMP(3),
    "newestIndexedAt"     TIMESTAMP(3),
    "lastIndexedAt"       TIMESTAMP(3),
    "createdAt"           TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"           TIMESTAMP(3) NOT NULL,
    CONSTRAINT "VoiceProfile_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "VoiceProfile_userId_key" ON "VoiceProfile"("userId");

ALTER TABLE "VoiceProfile" ADD CONSTRAINT "VoiceProfile_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "VoiceExample" (
    "id"                  TEXT NOT NULL,
    "userId"              TEXT NOT NULL,
    "emailMessageId"      TEXT NOT NULL,
    "gmailId"             TEXT NOT NULL,
    -- Classified relationship type. Enum-shaped but kept as TEXT so we
    -- can add new categories without a migration. Values match
    -- src/lib/voice/relationship-classifier.ts: former_student,
    -- peer_faculty, industry_exec, media, family, board, casual, unknown.
    "relationshipType"    TEXT NOT NULL,
    "openingType"         TEXT,
    "closingType"         TEXT,
    "wordCount"           INTEGER NOT NULL,
    "avgSentenceLen"      DOUBLE PRECISION NOT NULL,
    "signaturePhrases"    TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "sentAt"              TIMESTAMP(3) NOT NULL,
    "indexedAt"           TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "VoiceExample_pkey" PRIMARY KEY ("id")
);

-- Embedding stored via raw SQL since Prisma doesn't natively support vector.
-- 512 dims matches the Voyage voyage-3-lite model used elsewhere.
ALTER TABLE "VoiceExample" ADD COLUMN "embedding" vector(512);

CREATE UNIQUE INDEX "VoiceExample_emailMessageId_key" ON "VoiceExample"("emailMessageId");
CREATE INDEX "VoiceExample_userId_relationshipType_idx" ON "VoiceExample"("userId", "relationshipType");
CREATE INDEX "VoiceExample_userId_sentAt_idx" ON "VoiceExample"("userId", "sentAt" DESC);

ALTER TABLE "VoiceExample" ADD CONSTRAINT "VoiceExample_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "VoiceExample" ADD CONSTRAINT "VoiceExample_emailMessageId_fkey"
    FOREIGN KEY ("emailMessageId") REFERENCES "EmailMessage"("id") ON DELETE CASCADE ON UPDATE CASCADE;
