/**
 * One-shot data-fix for AssistantObservation rows whose content was
 * generated by the worker BEFORE 1333971 landed. Those rows have
 * literal "in web_mention" text in the content column because the
 * old phrasing template interpolated the internal enum.
 *
 * After 1333971 the worker writes clean copy, but existing rows
 * persist. This script does an in-place rewrite using the same
 * phrasing rules the new worker code uses.
 *
 * Idempotent — safe to re-run. No-op when there are no leaky rows.
 *
 * Usage:
 *   npx tsx scripts/fix-news-mention-observation-copy.ts
 */

import { PrismaClient } from "@/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

async function main() {
  const adapter = new PrismaPg({
    connectionString: process.env.DATABASE_URL!,
  });
  const prisma = new PrismaClient({ adapter });

  try {
    // Find rows where the buggy template fragment leaked through.
    // Two known patterns from production data:
    //   "<X> was mentioned recently in web_mention."
    //   (and possibly variants with .field for other ChangelogTypes)
    const leaky = await prisma.assistantObservation.findMany({
      where: {
        content: { contains: "web_mention" },
      },
      select: {
        id: true,
        content: true,
        source: true,
        contactId: true,
        sourceRefs: true,
      },
    });

    if (leaky.length === 0) {
      console.log("No leaky observation rows found. Nothing to fix.");
      return;
    }

    console.log(`Found ${leaky.length} observations to rewrite:`);
    let fixed = 0;

    for (const row of leaky) {
      // Pattern: "<Name> was mentioned recently in web_mention."
      // Replace the trailing template fragment with the new generic
      // phrasing. We don't have access to the original article title
      // here (it's on ContactChangelog.oldValue, fetchable via
      // sourceRefs), but the generic phrasing is good enough and
      // doesn't require a join.
      const next = row.content.replace(
        / was mentioned recently in web_mention\.?$/,
        " was mentioned in the news recently.",
      );
      if (next === row.content) {
        // Different leak shape than the known one — leave alone, the
        // operator can inspect.
        console.log(`  unmatched pattern: ${row.id} → ${row.content}`);
        continue;
      }
      await prisma.assistantObservation.update({
        where: { id: row.id },
        data: { content: next },
      });
      fixed++;
    }

    console.log(`Rewrote ${fixed} of ${leaky.length} rows.`);
  } finally {
    await prisma.$disconnect();
  }
}

main().catch((err) => {
  console.error("Script failed:", err);
  process.exit(1);
});
